services:
  - type: web
    name: destiny-web-rust
    runtime: rust
    plan: free
    buildCommand: cargo build --release
    startCommand: ./target/release/destiny-web-rust
    envVars:
      - key: FIREBASE_KEY_JSON
        sync: false
